# Generated by Django 6.1.1 on 2026-09-09 21:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_attendanceconfig_reportcard_status_staffattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcandidate',
            name='column',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examcandidate',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Hall this candidate was allocated to by the seating engine.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seated_candidates', to='school.room'),
        ),
        migrations.AddField(
            model_name='examcandidate',
            name='row',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='overflow_rooms',
            field=models.ManyToManyField(blank=True, help_text='Extra halls the seating engine may spill candidates into alongside `room`.', related_name='overflow_exam_papers', to='school.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='columns',
            field=models.PositiveIntegerField(blank=True, help_text='Seating columns for exam hall layouts, e.g. 10 for a 15x10 hall.', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='rows',
            field=models.PositiveIntegerField(blank=True, help_text='Seating rows for exam hall layouts, e.g. 15 for a 15x10 hall.', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_difficult',
            field=models.BooleanField(default=False, help_text='Flag cognitively demanding subjects (e.g. Maths, Physics) so the timetable engine spreads them across different days instead of clustering them.'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='periods_per_week',
            field=models.PositiveSmallIntegerField(default=5, help_text='How many timetable periods this subject/class pairing needs each week.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='room',
            field=models.ForeignKey(help_text='Primary/default hall. Add more halls via `overflow_rooms` for large candidate lists.', on_delete=django.db.models.deletion.PROTECT, related_name='exam_papers', to='school.room'),
        ),
    ]
