import { useState } from "react";
import { CalendarClock, LayoutGrid } from "lucide-react";
import { TimetableView } from "./TimetableView";
import { SeatingView } from "./SeatingView";

type Tab = "timetable" | "seating";

export function SchedulingPage() {
  const [tab, setTab] = useState<Tab>("timetable");

  return <div className="page-content">
    <div className="section-heading"><div><span className="eyebrow">Scheduling</span><h1>Timetables &amp; exam seating</h1><p className="muted">Generated by the OR-Tools CP-SAT solver and the adjacency-aware seating engine.</p></div></div>
    <div className="tab-bar">
      <button type="button" className={tab === "timetable" ? "tab active" : "tab"} onClick={() => setTab("timetable")}><LayoutGrid size={16} /> Timetable</button>
      <button type="button" className={tab === "seating" ? "tab active" : "tab"} onClick={() => setTab("seating")}><CalendarClock size={16} /> Exam seating</button>
    </div>
    <div className="panel">{tab === "timetable" ? <TimetableView /> : <SeatingView />}</div>
  </div>;
}
