# Generated by Django 6.1.1 on 2026-09-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='digital_token',
            field=models.CharField(blank=True, editable=False, max_length=28, null=True, unique=True),
        ),
    ]
